// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJlSGsBHOqQMGfnzYvt9XmtqzG4WiVfU',
    appId: '1:81338128048:web:3402490fcde4e93ef44d75',
    messagingSenderId: '81338128048',
    projectId: 'fortest-6f59d',
    authDomain: 'fortest-6f59d.firebaseapp.com',
    storageBucket: 'fortest-6f59d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxI-RkVqz6mxT1uc8o51F1i2aXbQCIUqw',
    appId: '1:81338128048:android:c28eb2f4d78d3d6df44d75',
    messagingSenderId: '81338128048',
    projectId: 'fortest-6f59d',
    storageBucket: 'fortest-6f59d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwhdQqC1f-Qphe-3YB48c6URXNK441nk',
    appId: '1:81338128048:ios:00784b4ba585ca15f44d75',
    messagingSenderId: '81338128048',
    projectId: 'fortest-6f59d',
    storageBucket: 'fortest-6f59d.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwhdQqC1f-Qphe-3YB48c6URXNK441nk',
    appId: '1:81338128048:ios:00784b4ba585ca15f44d75',
    messagingSenderId: '81338128048',
    projectId: 'fortest-6f59d',
    storageBucket: 'fortest-6f59d.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
